package controllers;
import models.Place;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import repositories.PlaceRepository;

@Controller
@RequestMapping(path="/places")
public class PlaceController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PlaceRepository placeRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String name
            , @RequestParam String imageUrl) {
        Place place = new Place(name, imageUrl);
        placeRepository.save(place);
        return "Saved";
    }
    @GetMapping(path="/all")
    public @ResponseBody Iterable<Place> getAllUsers() {
        // This returns a JSON or XML with the users
        return placeRepository.findAll();
    }

}
